name: Compile Ruleset

on:
  push:
    paths:
      - 'ruleset/**.json'
      - '.github/workflows/ruleset.yaml'
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download sing-box
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.11.3/sing-box-1.11.3-linux-amd64.tar.gz
          tar xvf sing-box-1.11.3-linux-amd64.tar.gz

      - name: Compile Rulesets
        run: |
          for json_file in ruleset/*.json; do
            filename=$(basename "$json_file" .json)
            ./sing-box-1.11.3-linux-amd64/sing-box rule-set compile --output "ruleset/${filename}.srs" "$json_file"
          done
          ls -l ruleset
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ruleset
          FOLDER: ruleset
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
